# General notes:
# - Paths are resolved relative to the working directory of the aresticrat
#   invocation and NOT relative to the config file.
# - Uncommented settings represent default values.
# - Commented out settings represent optional configuration examples.
# - Uppercase values in examples represent user-defined names.
#
# Special types:
# - COMMAND: A command consists of a program name followed by any number
#   (including none) of arguments. Values of this type have two possible forms:
#   - a sequence of strings (exec form), e.g. [ "program", "arg1", "arg2" ].
#     These strings are passed to the child process without additional
#     processing.
#   - a string (shell form), e.g. "program arg1 arg2". The string is processed
#     according to parsing rules of a Unix shell.

# The restic executable. Must be a name in PATH or a file path.
executable = "restic"


# The global backup settings.
# They apply to all locations that do not specify their own backup settings.
[options.backup]

# Whether to automatically run the forget command after every backup.
forget = false

# Supported exclude options.
# These correspond to restic options with the same names.
exclude-caches = false
exclude = [ ]
iexclude = [ ]
exclude-file = [ ]
iexclude-file = [ ]
exclude-if-present = [ ]
#exclude-larger-than = n

# If true, ignore ctime changes when checking for modified files.
ignore-ctime = false

# If true, ignore inode number and ctime changes when checking for modified
# files.
ignore-inode = false

# If true, do not run scanner to estimate size of backup.
no-scan = false

# If true, exclude other file systems, don't cross filesystem boundaries and
# subvolumes.
one-file-system = false

# If true, skip snapshot creation if identical to parent snapshot.
skip-if-unchanged = false

# If true, use filesystem snapshot where possible (currently only Windows VSS).
use-fs-snapshot = false

# If true, store the atime for all files and directories.
with-atime = false

# Commands that are run before a location backup is done.
# The location will be skipped if any of these commands does not terminate with
# an exit code of 0.
# Must be a sequence of COMMAND values.
hooks.if =  [ ]


# The global forget settings.
# They apply to all locations that do not specify their own forget settings.
[options.forget]

# Whether to automatically run the prune command if snapshots have been removed.
prune = false

# Keep the last n snapshots.
#keep-last = n
# Keep the last n hourly, daily, weekly, monthly or yearly snapshots.
#keep-hourly = n
#keep-daily = n
#keep-weekly = n
#keep-monthly = n
#keep-yearly = n

# Keep snapshots that are newer than duration (e.g. 1y5m7d2h) relative to the
# latest snapshot.
#keep-within = duration
# Keep hourly, daily, weekly, monthly or yearly snapshots that are newer than
# duration (e.g. 1y5m7d2h) relative to the latest snapshot.
#keep-within-hourly = duration
#keep-within-daily = duration
#keep-within-weekly = duration
#keep-within-monthly = duration
#keep-within-yearly = duration

# Keep snapshots with this tag list.
keep-tag = [ ]

# Commands that are run before a location forget is done.
# The location will be skipped if any of these commands does not terminate with
# an exit code of 0.
# This hook is not executed if the forget is done as part of a backup.
# Must be a sequence of COMMAND values.
hooks.if =  [ ]


# The environment variables that will be applied to all repositories unless they
# overwrite these values.
# Note that variables defined here cannot alter the configuration, so
# ARESTICRAT_ variables will have no effect. Instead, define them exactly as you
# would when passing them directly to restic (e.g., RESTIC_PASSWORD instead of
# ARESTICRAT_R_SOMEREPO_RESTIC_PASSWORD).
[environment]
env-files = [ ]
#vars.VAR1=foo
#vars.VAR2=bar



### LOCATION SYNTAX ###

# The header defines the location name.
# The name is used to refer to this location from other parts of the
# configuration or the CLI.
#[locations.LOCATION]

# Paths that should be stored in restic repositories (at least one required).
# The key "from" is an alias and may be used instead of "paths".
#paths = [ "/path/to/data" ]

# Repositories that should be used to store the data.
# The key "to" is an alias and may be used instead of "repos".
#repos = [ "REPOSITORY" ]

# Any "options.*" table from above may also be declared for a repository.
# These location-specific sections replace the global sections, meaning that
# none of the global options are applied, even if there are no corresponding
# keys in the location-specific section.
#[locations.LOCATION.options.(backup|forget|...)]
#...


# EXAMPLE: Minimal location configuration.
# - Stores data from a single path.
# - Stores data in a single repository.

#[locations.userhomes]
#paths = [ "/home" ]
#repos = [ "remote" ]


# EXAMPLE: Extensive location configuration.
# - Stores data from multiple paths.
# - Stores data in multiple repositories.
# - Specifies its own forget policy.
# - Specifies what data to exclude.

#[locations.system]
#from = [ "/etc", "/root", "/usr/local", "/var" ]
#to = [ "local", "remote" ]

#[locations.system.options.forget]
#prune = true
#keep-hourly = 48
#keep-daily = 14
#keep-weekly = 4
#keep-monthly = 6
#keep-yearly = 0

#[locations.system.options.backup]
#exclude-caches = true
#exclude = [ "/var/cache" ]
#iexclude = [ "*.tmp", "*.temp", "*.cache" ]
#exclude-file = [ "/backup/excludes/common" ]
#iexclude-file = [ "/backup/excludes/i-common" ]



### REPOSITORY SYNTAX ###

# The header defines the repository name.
# The name is used to refer to this repository from other parts of the
# configuration or the CLI.
#[repos.REPOSITORY]

# The path to this repository. That's the value that would be passed to restic's
# -r/--repo option.
#path = "a/restic/repository/path"

# The repository key (password). Any of the following options will work. For
# better security, prefer passing the password via password-file or
# password-command instead of storing it in plaintext here.
#password = "unique_long_secret_value"
#key = "unique_long_secret_value" # (deprecated, use password instead)
#password-file = "path/to/secret/file"
#password-command = "bash -c cat /path/to/secret/file"

# Repository-specific environment variables. Note that environment files listed
# in this section are added to those defined globally.
#[repos.REPOSITORY.environment]
#env-files = [ ]
#vars.VAR1=foo
#vars.VAR2=bar



# EXAMPLE: Local repository.
#[repos.local]
#path = "/backup/restic-repo"
#password = "secret_local_repo_key"


# EXAMPLE: Remote repository.
#[repos.remote]
#path = "sftp:user@host:/srv/restic-repo"
#password = "secret_sftp_repo_key"
