name: Push Actions
run-name: ${{ gitea.actor }} is building.

on:
  push:
    branches-ignore:
      - 'wip/**'
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-musl]
        version: [1.75.0, stable, nightly]
    env:
      RUSTUP_HOME: /usr/local/rustup
      CARGO_HOME: /usr/local/cargo
      RUSTUP_VERSION: 1.27.0
      RUST_VERSION: ${{ matrix.version }}
      RUST_ARCH: x86_64-unknown-linux-gnu
      RUST_TARGET: ${{ matrix.target }}
    steps:
      - name: Add rust binary directory to PATH
        run: echo "/usr/local/cargo/bin" >> $GITHUB_PATH
      - name: Restore rust toolchain
        uses: actions/cache/restore@v4
        id: restore-toolchain-cache
        with:
          key: cache-rust-toolchain-${{ runner.os }}
          path: |
            ${{ env.CARGO_HOME }}/
            ${{ env.RUSTUP_HOME }}/
      - name: Install rust toolchain
        run: |
          if ! command -v rustup &> /dev/null; then
            wget "https://static.rust-lang.org/rustup/archive/$RUSTUP_VERSION/$RUST_ARCH/rustup-init"
            chmod +x rustup-init
            ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host $RUST_ARCH
            rm rustup-init
          fi
          chmod -R a+w $RUSTUP_HOME $CARGO_HOME
          rustup default $RUST_VERSION
          rustup target add $RUST_TARGET
          rustup --version
          rustc --version
          cargo --version
      - name: Update rust toolchain cache
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-toolchain-cache.outputs.cache-primary-key }}
          path: |
            ${{ env.CARGO_HOME }}/
            ${{ env.RUSTUP_HOME }}/
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Restore cached build artifacts
        uses: actions/cache/restore@v4
        id: restore-build-cache
        with:
          key: cache-cargo-${{ runner.os }}-${{ gitea.repository }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cache-cargo-${{ runner.os }}-${{ gitea.repository }}-
            cache-cargo-${{ runner.os }}-
          path: |
            ${{ env.CARGO_HOME }}/git
            ${{ env.CARGO_HOME }}/registry
            target/
      - name: Run tests
        run: cargo test --target=$RUST_TARGET
      - name: Update build artifacts cache
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.restore-build-cache.outputs.cache-primary-key }}
          path: |
            ${{ env.CARGO_HOME }}/git
            ${{ env.CARGO_HOME }}/registry
            target/
